package db

import (
	"database/sql"
	"fmt"
	"log"
	"os"
	"strconv"

	"github.com/joho/godotenv"
	_ "github.com/lib/pq"
)

var DB *sql.DB

func CheckError(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func Connect_db() {
	loadenv := godotenv.Load()
	CheckError(loadenv)
	var (
		HOST     = os.Getenv("DB_HOST")
		PORT, _  = strconv.Atoi(os.Getenv("DB_PORT"))
		DBNAME   = os.Getenv("POSTGRES_DB")
		USERNAME = os.Getenv("POSTGRES_USER")
		PASSWORD = os.Getenv("POSTGRES_PASSWORD")
	)
	psqlInfo := fmt.Sprintf("host=%s port=%d user=%s "+
		"password=%s dbname=%s sslmode=disable",
		HOST, PORT, USERNAME, PASSWORD, DBNAME)

	sdb, err := sql.Open("postgres", psqlInfo)
	CheckError(err)
	DB = sdb

	err = DB.Ping()
	CheckError(err)
	databaseExists()
}

func databaseExists() {
	_, err := DB.Exec(
		"CREATE TABLE IF NOT EXISTS todos (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,title TEXT,completed BOOLEAN,created_at DATE);")

	CheckError(err)
}